version: '3.8'
services:
  postgres_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data5/
    env_file:
      - ./.env
  redis_db:
    image: redis:7.0-alpine
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - ./.env
    command: redis-server --requirepass REDIS_PASSWORD
    volumes: 
      - cache:/data
  backend:
    image: konstantin05/fastapidiploma:latest
    expose:
      - 8000
    restart: always
    # volumes:
    #   - static_value:/app/backend_static/
    #   - media_value:/app/backend_media/
    env_file:
      - ./.env
    depends_on:
      - redis_db
      - postgres_db
  # nginx:
  #   image: nginx:1.21.3-alpine
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ../frontend/build:/usr/share/nginx/html/
  #     - ../docs/redoc.html:/usr/share/nginx/html/api/docs/redoc.html
  #     - ../docs/openapi-schema.yml:/usr/share/nginx/html/api/docs/openapi-schema.yml
  #     - static_value:/app/backend_static/
  #     - media_value:/app/backend_media/
  #   restart: always
  #   depends_on:
  #     - frontend
  # frontend:
  #     image: konstantin05/foodgram_frontend:latest
  #     volumes:
  #       - ../frontend/:/app/result_build/
volumes:
  postgres_data:
  cache:
